### ISSUE TITLE
Text Blocks and Block Quotes not working with special characters

### ISSUE THREAD

**Issue by Felixmil** [encounterplus/module-packer#16]
I like to use bullet point. A lot.

I noticed that when using bullet points in text/quote/read/paper blocks, the style is not applied to the block.

here only with `{.paper}` in vscode preview:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/34234913/88768429-60985500-d17b-11ea-88c5-3d3ae509c3cc.png">

**Is it expected behavior ? If not, how can I help fix this ?**

**Comment by MrFarland** [comment]
Add a blank line '> ' after the list and it should take the style, as in block 4. It is a known issue.

**Comment by Felixmil** [comment]
Sure, that's what I'm doing right now. 

But i'm sure you agree that the best solution would be to find a robust and long term fix for this issue. I know it is a small thing and probably not very urgent but I feel I could help on this one.

So @jacobjohnston, how can I help with this ?

**Comment by jacobjohnston** [comment]
This is a limitation of the markdown attributes extension. In the case you've shown, it is actually applying the attribute, but it is applying it to the `<ul>` element rather than the `<blockquote>` element like you want. It doesn't know your intentions to move it out an extra layer. You can see this if you take a look at the generated HTML in the VS Code preview window:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1703107/89455805-b6d73c00-d717-11ea-81ac-1183ae4def0b.png">

I actually have a way to resolve this without the extra line - by using the [markdown-it-decorate extension](https://github.com/rstacruz/markdown-it-decorate) (which is already part of Module Packer), but I haven't documented that extension in the Readme yet. This extension allows you to target elements more-specifically with an HTML-comment style syntax:

```Markdown
> - This is a bullet
<!-- {blockquote: .paper} -->
```

I think I would like to document this as an "advanced" feature.

I'm open to hearing more about alternative approaches, but I think it will be a bit challenging to coerce this into knowing you're referring to the blockquote rather than the list.

**Comment by jacobjohnston** [comment]
Closing this as it is documented in the Advanced.md now
