### ISSUE TITLE
images are not Visible for items handouts like monsters

### ISSUE THREAD

**Issue by Felixmil** [encounterplus/module-packer#54]
In the example module, we can see that the `image:` argument for monster block is in the preview:

```yaml
...
image: Images/Monster.jpg
...
```
![image](https://user-images.githubusercontent.com/34234913/150301694-0c87e8cf-8271-481b-a240-2f53159bf109.png)

![image](https://user-images.githubusercontent.com/34234913/150301275-b62e4b1a-5ecd-420f-8f17-d00a36714cf5.png)

However, this is not the case for Items:
```yaml
...
image: ShoePlusFour.jpg
```
![image](https://user-images.githubusercontent.com/34234913/150301856-a702741a-f0cc-4e4e-b740-ea329903cd11.png)

![image](https://user-images.githubusercontent.com/34234913/150301552-7dc8f772-5372-49f6-90f5-7759e6c81d8c.png)

**Comment by cffs** [comment]
I observe this bug too.
The image is actually included in the module and is visible in Encounter+ from the compendium entry, but not in the page where the item is defined.

**Comment by jacobjohnston** [comment]
This wasn't so much as a bug as something I intentionally never added because I never thought it looked good (and other platforms like D&D Beyond don't do the image in the block - but rather, outside the block on the page). That said, I've added the ability to do this in the next version. Simply add `show-image: true` and it will display it with the block. Applies to both spells and items.
