### ISSUE TITLE
Exported Map's Background Image Not Appearing on iOS Import

### ISSUE THREAD

**Issue by custompro98** [encounterplus/module-packer#56]
First, this tool is fantastic for creating adventure pages to be imported on the iOS E+ app. I've recently added on the map feature for E+ and have been trying to export my map in the bundled module.

The map appears in the module and the walls are present when I switch to the walls layer, but my map's image is not properly importing. The iOS app is unable to import the generated `.module` file that is importable by the Mac app, so I've been importing the `module.xml` file inside of the `ModuleBuild` folder. I see the `image` tag in the `module.xml` and it matches the image that is included in the folder.

Any advice on properly importing the map images?

It's worth noting that the same occurs for me when using the Cultist Hideout example in the examples.zip file.

**Comment by jacobjohnston** [comment]
I want to make sure I'm understanding everything correctly, because I'm not able to reproduce this.
- You're not able to import the `.module` file, so you're attempting to importing the `module.xml` file directly? I didn't even realize E+ allowed you to attempt importing the `module.xml` until now - but yeah, absolutely no images will work if you do that (not just maps).
- Is there a mode where you've imported the `.module` file and no images have shown up? Or, have you just never gotten that far and that is why you attempted to import just the `module.xml` file?
- I'd like to understand why the `.module` files don't import. That sounds like the real bug here. Do you have a broken `.module` file I can take a look at? Does the Cultist Hideout `.module` file not import either?

**Comment by jacobjohnston** [comment]
P.S. - A `.module` file is basically nothing but a zip file of everything in your ModuleBuild folder. You can rename a `.module` file to `.zip` to inspect it.

**Comment by custompro98** [comment]
Thanks for the response! Good to know that a `.module` file is just a zip.

* Correct I am unable to import the `.module` file so I am importing the `module.xml` file directly. Good to know that's the wrong file to upload. And it makes sense because the images are probably bundled in the `.module` zip, so I'm not actually importing those assets. Probably explains why my monster images weren't importing correctly either.
* The iOS app leaves the `.module` file unselectable (grayed out) when choosing a file for import.
* The Cultist Hideout example's `.module` file is not selectable either.

I ran the module packer via the VS Code extension. But that appears to run the same command as the dedicated application.

**Comment by custompro98** [comment]
I did some more digging and it seems like it's an issue with iOS not allowing arbitrary filetypes to be opened from Google Drive with an app. The following approaches worked:

1. Open the Google Drive app, navigate to the `.module` file, three dots, open in, Encounter+
2. Open the Google Drive app, navigate to the `.module` file, three dots, save to file, Import via Encounter+ menu.

I apologize for opening a non-issue.
