### ISSUE TITLE
Incorrect header style in default text block

### ISSUE THREAD

**Issue by JordyProvost** [encounterplus/module-packer#59]
Hi Jacob,

When inserting a title in a default text block, the result is not like the one in README.md.
The document default header Police/Size is applied.

```
> ### HEADING - IN BLOCK QUOTE
> Some text 1
> Some test 2
> Some text 3
```

Thanks !

**Comment by jacobjohnston** [comment]
Headings have a lot of implications in module-packer (particular as they pertain to page breaks). I chose to remove this styling because of how it would break headings. If you want the style shown in the Readme, it's just bolded, capitalized text. I'll update the Readme to be a bit more clear on that.

```Markdown
> **BLOCKQUOTE TITLE**
> 
> Pretium lectus quam id leo in vitae turpis massa. Nunc scelerisque viverra mauris in aliquam. Lacus viverra vitae congue eu consequat. 
> 
> Semper risus in [hendrerit](/page/hendrerit) gravida rutrum quisque non tellus. Vel fringilla est ullamcorper eget nulla [facilisi](/monster/facilisi) etiam. Neque [laoreet](/item/laoreet) suspendisse interdum [consectetur](/spell/consectetur). Bibendum neque egestas congue quisque egestas diam in arcu cursus.
```

**Comment by JordyProvost** [comment]
Ok, thank you for the information !
